# user_input.yml corresponds to the default parameters that can be found in the stage SQL queries 
# Those are always played if not overwritten by user_input_override.yml in the same folder
user_input:
  sqlserver3411_host: "192.168.34.11,1433" 
  sqlserver3411_database: "Salesforce_DB"
  sqlserver3411_driver: "ODBC Driver 17 for SQL Server"
  sqlserver3411_auth: "windows"       
  sqlserver3411_trust_cert: "yes"
  oracle_host: "192.168.34.8"
  oracle_port: "1521"
  oracle_user: 
  oracle_password: 
  oracle_sid: "ORA10"
  oracle_database: "IBERICA"
  oracle_mode: thick
  oracle_lib_dir: "X:/oracle/instantclient-21.18"
  studio_host: "ibedata.database.windows.net" 
  studio_database: "ibeData"
  studio_user: 
  studio_password: 
  studio_driver   : "ODBC Driver 17 for SQL Server" 
  azure_trust_cert: "no" 