# user_input.yml corresponds to the default parameters that can be found in the stage SQL queries 
# Those are always played if not overwritten by user_input_override.yml in the same folder
user_input:
  salesforce_host: "192.168.34.11,1433" 
  salesforce_database: "Salesforce_DB"
  salesforce_driver: "ODBC Driver 17 for SQL Server"
  salesforce_auth: "windows"       
  salesforce_trust_cert: "yes"
  oracle_host:
  oracle_user:
  oracle_password: 
  oracle_database: